version: 0.0
os: linux
files:
files:
  - source: /
    destination: /trinimbus-app
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  AfterInstall:
    - location: scripts/after_install.sh
  ApplicationStart:
    - location: scripts/db_setup.sh
      timeout: 180
    - location: scripts/app_start.sh
      timeout: 30