version: 0.0
os: linux
permissions:
  - object: /home/ubuntu/deployment
    owner: ubuntu
    mode: 755
    type:
      - directory
      - file
files:
  - source: /
    destination: /home/ubuntu/deployment/app/
hooks:
  BeforeInstall:
    - location: scripts/app_stop.sh
      runas: root
  AfterInstall:
    - location: scripts/app_set.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/app_start.sh
      runas: root