version: 0.0
os: linux
permissions:
  - object: /home/ubuntu/deployment
    owner: ubuntu
    mode: 755
    type:
      - directory
      - file
files:
  - source: /
    destination: /home/ubuntu/deployment/app
hooks:
  BeforeInstall:
    - location: /home/ubuntu/deployment/app/scripts/before_install.sh
  AfterInstall:
    - location: /home/ubuntu/deployment/app/scripts/restore_and_build.sh
    - location: /home/ubuntu/deployment/app/scripts/db_setup.sh
    - location: /home/ubuntu/deployment/app/scripts/publish_and_run.sh