version: 0.0
os: linux
permissions:
  - object: /home/ec2-user/deployment
    pattern: "*"
    owner: ec2-user
    mode: 755
    type:
      - directory
files:
  - source: /
    destination: /home/ec2-user/deployment/app
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  AfterInstall:
    - location: scripts/after_install.sh
  ApplicationStart:
    - location: scripts/db_setup.sh
      timeout: 180
    - location: scripts/app_start.sh
      timeout: 30