version: 0.0
os: linux
permissions:
  - object: /home/ubuntu/deployment
    owner: ubuntu
    mode: 755
    type:
      - directory
      - file
files:
  - source: /
    destination: /home/ubuntu/deployment/app
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  AfterInstall:
    - location: scripts/after_install.sh
  ApplicationStart:
    - location: scripts/db_setup.sh
      timeout: 180
    - location: scripts/app_start.sh
      timeout: 30